# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '3.0.x'

- script: dotnet --info
  displayName: 'Display .NET Core information'

- script: dotnet pack --configuration $(buildConfiguration)
  displayName: 'Build and package'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: 'test/*.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'